version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    container_name: apptest
    environment:
      - APP_HOSTNAME=apptest
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    environment:
      - SE_START_XVFB=false
      - SE_SESSION_REQUEST_TIMEOUT=3600
    ports:
      - 4444:4444
      - 7900:7900





