name: 'build and deploy to heroku(test) && docker hub'

on:
  release:
    types: [published]

jobs:
  push_to_docker_hub:
    name: 'Build production image & Push to Docker hub'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build mvn deps image
        run: docker build -f Dockerfile.deps . -t deps:latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v3
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/shop_inventory_pos:${{ github.event.release.tag_name }}, ${{ secrets.DOCKERHUB_USERNAME }}/shop_inventory_pos:latest

      - name: Build, Push and Release to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
            email: ${{ secrets.HEROKU_EMAIL }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            dockerfile_directory: ./
            dockerfile_name: Dockerfile.heroku
            docker_options: "--no-cache"
            process_type: web