name: 'build and deploy to heroku(test) && docker hub'

on:
  release:
    types: [published]

jobs:
  push_to_docker_hub:
    name: 'Build production image & Push to Docker hub'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building deps image
        uses: docker/build-push-action@v3
        with:
            context: .
            file: ./Dockerfile.deps
            tags: deps:latest
            outputs: type=docker,dest=/tmp/deps.tar

      - name: test
        run: docker image ls

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: deps
            path: /tmp/deps.tar

      - name: Build and push app image
        uses: docker/build-push-action@v3
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/shop_inventory_pos:${{ github.event.release.tag_name }}, ${{ secrets.DOCKERHUB_USERNAME }}/shop_inventory_pos:latest

  deploy_to_heroku:
    name: 'Build tests image & Deploy to Heroku'
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
            name: deps
            path: /tmp

      - name: Load deps image
        run: docker load --input /tmp/deps.tar

      - name: test
        run: docker image ls

      - name: Build, Push and Release to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
            email: ${{ secrets.HEROKU_EMAIL }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            dockerfile_directory: ./
            dockerfile_name: Dockerfile.heroku
            docker_options: "--no-cache"
            process_type: web