
name: Testing on requests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Build mvn deps image
         run: docker build -f Dockerfile.deps . -t deps:latest

       - name: Run tests
         run: docker-compose -f docker-compose.test.yml up
