
name: Testing on requests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Build mvn deps image
         run: |
              sed -i "/\b\(WORKDIR\)\b/d" Dockerfile.deps
              docker build -f Dockerfile.deps . -t deps:latest

       - name: Set github actions reqs
         run: |
              sed -i "/\b\(WORKDIR\)\b/d" Dockerfile.test
              sed -i "/\b\(CMD\)\b/d" Dockerfile.test
              sed -i "/\b\(WORKDIR\)\b/d" .env
              echo "USER 1001:1001" >> Dockerfile.test
              echo "CMD mvn test" >> Dockerfile.test
              cat Dockerfile.test
              echo "WORKDIR=${GITHUB_WORKSPACE}" >> .env
              cat .env

       - name: Run tests
         run: docker-compose -f docker-compose.test.yml up --exit-code-from test
         env:
           EMAIL_ROBOT_NAME: ${{secrets.EMAIL_ROBOT_NAME}}
           EMAIL_ROBOT_PASS: ${{secrets.EMAIL_ROBOT_PASS}}

