
name: Testing on requests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build environment
        run: docker-compose -f docker-compose.test.yml up
